on:
  push:
    branches:
     - main
  pull_request:
    branches:
     - main
  workflow_dispatch:
jobs:
  my_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run Python Script
        run: python main.py
